name: econova_marketplace
description: EcoNova Marketplace - A sustainable product marketplace app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  provider: ^6.0.5
  lottie: ^3.1.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/lottie/
