// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCURIlDZ_eKvl1DCslrzfDccWzN1G93NaI',
    appId: '1:345816520721:android:03c7fa557d55b2e782b9b0',
    messagingSenderId: '345816520721',
    projectId: 'econova-962d3',
    databaseURL: 'https://econova-962d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'econova-962d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEs0abcFKB1RDxBC7iHDxI6t1okdQCrNE',
    appId: '1:345816520721:ios:5ebd28612381b7d882b9b0',
    messagingSenderId: '345816520721',
    projectId: 'econova-962d3',
    databaseURL: 'https://econova-962d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'econova-962d3.firebasestorage.app',
    iosClientId: '345816520721-kev9h195qms8gr99eguipo8dj4dhhil2.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
